#!/bin/bash

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Customer reported login issues on mobile app. User ID: CUS123. Issue: Unable to login after recent app update 2.1.0. Error message shows '\''Authentication failed'\''. Steps taken: 1. Cleared app cache 2. Reset password 3. Verified email is verified. Resolution: Bug found in authentication module for iOS devices, pushed hotfix 2.1.1.", "metadata": {"ticket_id": "T-1001", "category": "Authentication", "priority": "High", "status": "Resolved", "platform": "iOS"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Payment processing failure reported. Customer attempted to make a purchase of $299.99. Transaction ID: TRX789. Error occurred during payment gateway integration. Customer receiving error '\''Transaction declined'\''. Investigation showed expired SSL certificate on payment gateway. Certificate renewed and transaction processed successfully.", "metadata": {"ticket_id": "T-1002", "category": "Payment", "priority": "Critical", "status": "Resolved", "platform": "Web"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Data sync issue between mobile and web platform. Customer ID: CUS456. Customer reports that tasks created on mobile are not appearing on web interface. Sync delay observed of approximately 30 minutes. Root cause: Redis cache invalidation timing issue. Fixed by adjusting cache refresh intervals.", "metadata": {"ticket_id": "T-1003", "category": "Sync", "priority": "Medium", "status": "Resolved", "platform": "Cross-platform"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Performance degradation in dashboard loading. Customer reported 15+ second load time for main dashboard. Investigation revealed inefficient database queries and missing indexes. Optimization applied: Added composite index on frequently queried columns, implemented query caching. Load time reduced to 2 seconds.", "metadata": {"ticket_id": "T-1004", "category": "Performance", "priority": "High", "status": "Resolved", "platform": "Web"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Export functionality not working for large datasets. Customer attempting to export 50,000 records as CSV. Export job timing out after 30 seconds. Solution implemented: Added background job processing for large exports, sending email notification when export is ready for download.", "metadata": {"ticket_id": "T-1005", "category": "Data Export", "priority": "Medium", "status": "Resolved", "platform": "Web"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Push notification not working on Android devices. Customer ID: CUS789. Android version: 13. Firebase configuration issue identified. Token refresh not happening properly. Fixed by updating Firebase SDK and implementing proper token refresh mechanism.", "metadata": {"ticket_id": "T-1006", "category": "Notifications", "priority": "High", "status": "Resolved", "platform": "Android"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "API rate limiting issues for enterprise customer. Customer hitting rate limit of 100 requests/minute. Business requirement is for 500 requests/minute. Updated rate limiting policy for enterprise tier accounts. Implemented redis-based rate limiting with proper monitoring.", "metadata": {"ticket_id": "T-1007", "category": "API", "priority": "High", "status": "Resolved", "platform": "API"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Custom report generator throwing errors. Error occurs when including calculated fields. SQL query timing out for complex calculations. Optimized query performance by implementing materialized views and adding appropriate indexes. Added caching layer for frequently accessed reports.", "metadata": {"ticket_id": "T-1008", "category": "Reporting", "priority": "Medium", "status": "Resolved", "platform": "Web"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "SSO integration failure with Okta. Customer unable to login using Okta SSO. Error in SAML assertion validation. Configuration issue identified in SP metadata. Updated SAML certificates and fixed audience URI configuration.", "metadata": {"ticket_id": "T-1009", "category": "Authentication", "priority": "Critical", "status": "Resolved", "platform": "Web"}}' && \

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Billing automation system double-charging customers. Affected period: March 2024. Root cause: Race condition in payment processing webhook handler. Implementation of idempotency keys and transaction logs. Refunds processed for all affected customers.", "metadata": {"ticket_id": "T-1010", "category": "Billing", "priority": "Critical", "status": "Resolved", "platform": "System"}}'

curl -X POST "http://localhost:8000/knowledge/add" -H "Content-Type: application/json" -d '{"text": "Hello World, we are two engineers Arpit and Amandeep who have built this beautiful company. Our Birbal assistant will help you with anything related to your coompany knowledge from slack, telegram, email, website or anything. Be it any source of info we will collect that data and create a Knoledgebase for you which will empower you and your company like never before. So what are you waiting for contact use at our email: contact@insightful.com", "metadata": {"ticket_id": "", "category": "company-knowledge", "priority": "Critical", "status": "", "platform": "Company"}}'

